name: CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ./rdb-devops
        docker-compose up --build -d
        cd ..
        cd ./devops
        docker-compose up --build -d
